### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by lordmundi**
I added a new command so that I could specify the service name.  I implemented it with a whole new command so as to not break existing scripts, but see my commit message for my thoughts here.  I'm thinking that if you decide to keep the functionality, you might consider allowing an optional "-name" argument to the register command to avoid the duplicate commands.

FG

### CODE REVIEW

**Comment by dongola7** [comment]
Thanks for the submission.  I like the idea of including support for explicitly specifying the service name, but I thought the code, as written, introduced a lot of duplication.  Rather than add the new "register_with_name" command, I took your recommendation and added the "-name" option to the existing "register" command.

Let me know if this doesn't get you what you need.  I pushed the changes this evening and also bumped the version to 1.1.

**Comment by lordmundi** [comment]
my thoughts exactly.  i'll pull in your latest and try the new switch.  while you are editing this, i think it might be useful to have a new command which will let us complete the service resolve process.  Once we browse, we are able to then resolve using your commands which is great, but this only gives us the hostname and port.  The documentation for bonjour says that we can call "DNSServiceQueryRecord" to get the address for a particular hostname.  If we had a quick tcl command in the package that lets us take the hostname coming from the resolve callback and get the ip, that would be great.  I'm thinking a general "::bonjour::gethostbyname" function would make this very easy.

the documentation I was reading about resolving a service all the way to an IP address is here:

http://developer.apple.com/library/mac/#documentation/Networking/Conceptual/dns_discovery_api/Articles/resolving.html#//apple_ref/doc/uid/TP40002487-SW1

FG

**Comment by dongola7** [comment]
I created a new request for the hostname resolution item.

**Comment by dongola7** [comment]
I added a new resolve_address command.  Give it a whirl and let me know if it's what you're looking for.

**Comment by dongola7** [comment]
Closing this feature request since the -name option has been added to bonjour::register.

**Pull request closed without merging**
